parameters:
    mail_template:
        main_color: "#333"
        background_color: "#f7f7f7"
        section_title_color: "#FFF"
        logo: "http://directorofawesome.com/wp-content/uploads/2017/09/slacklogo.png"
        company_name: 'Awesome Company'

        base_slack_url: 'https://awesome.slack.com'
        summary: |
            We attach particular importance to the technological watch which is at the heart of our business.
            Here is a weekly summary of what we shared on Slack.

    blacklist_urls:
        - "slack.com/?redir="
        - "slack.com/files/"
        - "giphy.com/"

    mail_sender: "news@example.com"

    days_to_browse: 1
    locale: 'en'
