# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    slack_token: '%env(SLACK_TOKEN)%'
    env(CHANNELS_FILE): '%kernel.project_dir%/config/channels.json'
    slack_channels: '%env(json:file:CHANNELS_FILE)%'
    news_receivers: '%env(csv:RECEIVERS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $slackToken: '%slack_token%'
            array $blocklistUrls: '%blocklist_urls%'
            int $daysToBrowse: '%days_to_browse%'
            string $publicDir: '%kernel.project_dir%/public/'
            array $mailTemplate: '%mail_template%'
            array $newsReceivers: '%news_receivers%'
            string $mailSender: '%mail_sender%'

    App\:
        resource: '../src/*'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
