# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    slack_token: '%env(SLACK_TOKEN)%'
    env(CHANNELS_FILE): '%kernel.project_dir%/config/channels.json'
    env(RECEIVERS_FILE): '%kernel.project_dir%/config/receivers.json'
    slack_channels: '%env(json:file:CHANNELS_FILE)%'
    news_receivers: '%env(json:file:RECEIVERS_FILE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $slackToken: '%slack_token%'
            $slackChannels: '%slack_channels%'
            $blacklistUrls: '%blacklist_urls%'
            $daysToBrowse: '%days_to_browse%'
            $publicDir: '%kernel.project_dir%/public/'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\Newsletter\RenderService:
        arguments:
            - '@twig'
            - '%mail_template%'

    App\Command\AppNewsletterSendCommand:
        bind:
            $newsReceivers: '%news_receivers%'
            $mailSender: '%mail_sender%'

    Symfony\Component\Mailer\Mailer:
        arguments: ['@mailer.transport']
    Symfony\Component\Mailer\MailerInterface: '@Symfony\Component\Mailer\Mailer'
    mailer.transport:
        class: Symfony\Component\Mailer\Transport\TransportInterface
        factory:
            - 'Symfony\Component\Mailer\Transport'
            - fromDsn
        arguments:
            - '%env(MAILER_DSN)%'
            - '@event_dispatcher'
