name: CI

on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    check:
        runs-on: ubuntu-latest
        name: Validate code
        steps:
            -
                name: Checkout 🛎️
                uses: actions/checkout@v2
                with:
                    persist-credentials: false
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  coverage: none
            - run: composer install --no-progress --no-interaction
            - name: PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff
            - name: Lint YAML
              run: bin/console lint:yaml config/
            - name: Lint container
              run: bin/console lint:container --env=prod
